// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP9w3xGMySqal7j7AASNoPoI24N5G_Swo',
    appId: '1:730574833504:web:9f6d025e6b8dd2d5d78005',
    messagingSenderId: '730574833504',
    projectId: 'android-apps-86a5b',
    authDomain: 'android-apps-86a5b.firebaseapp.com',
    storageBucket: 'android-apps-86a5b.appspot.com',
    measurementId: 'G-HN1L7BHB3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi873InUU0vgLSho9f9ziNF1eUHDE9b5I',
    appId: '1:730574833504:android:63ce628a7ece7bbbd78005',
    messagingSenderId: '730574833504',
    projectId: 'android-apps-86a5b',
    storageBucket: 'android-apps-86a5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWKwK11FYWI12YpkkmJwZWeaOgELoqinU',
    appId: '1:730574833504:ios:bbedbf9de3df034dd78005',
    messagingSenderId: '730574833504',
    projectId: 'android-apps-86a5b',
    storageBucket: 'android-apps-86a5b.appspot.com',
    iosClientId: '730574833504-lfusr4r9kj0pqhom703tg591dav901ao.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWKwK11FYWI12YpkkmJwZWeaOgELoqinU',
    appId: '1:730574833504:ios:fb83e047bbcb2486d78005',
    messagingSenderId: '730574833504',
    projectId: 'android-apps-86a5b',
    storageBucket: 'android-apps-86a5b.appspot.com',
    iosBundleId: 'com.example.pushNotification.RunnerTests',
  );
}
